// ============================================================
// SerkoGram — Unified Command Registry (Source of Truth)
// Covers both Dot Commands (.) and Slash Commands (/)
// ============================================================

export type CommandPrefix = '.' | '/' | '.|/';

export type CommandCategory =
  | 'main'
  | 'info'
  | 'archive'
  | 'games'
  | 'ai'
  | 'translation'
  | 'animations'
  | 'media'
  | 'fun'
  | 'automation'
  | 'mirror'
  | 'utility';

export type ResponseMode =
  | 'PUBLIC_CHAT'
  | 'OWNER_PRIVATE'
  | 'MINI_APP'
  | 'SILENT'
  | 'SAME_CHAT'
  | 'REPLY'
  | 'EDIT';

export interface CommandCategoryInfo {
  id: CommandCategory;
  name: string;
  description: string;
  icon: string;
}

export const COMMAND_CATEGORIES: CommandCategoryInfo[] = [
  { id: 'main', name: 'Основные', description: 'Базовые функции и навигация', icon: 'Sparkles' },
  { id: 'info', name: 'Информация', description: 'О сервисе, чате и собеседнике', icon: 'Info' },
  { id: 'archive', name: 'Архив', description: 'Сообщения, удалённые и медиа', icon: 'Archive' },
  { id: 'games', name: 'Игры', description: 'Интерактивные мини-игры', icon: 'Gamepad2' },
  { id: 'ai', name: 'Нейросеть', description: 'Искусственный интеллект и генерация', icon: 'Bot' },
  { id: 'translation', name: 'Перевод', description: 'Перевод сообщений в чате', icon: 'Languages' },
  { id: 'animations', name: 'Анимации', description: 'Анимированные текстовые эффекты', icon: 'Film' },
  { id: 'media', name: 'Медиа', description: 'Сохранение медиа и видео', icon: 'Image' },
  { id: 'fun', name: 'Приколы', description: 'Развлекательные команды', icon: 'Smile' },
  { id: 'automation', name: 'Автоматизация', description: 'Автоответчики и таймеры', icon: 'Clock' },
  { id: 'mirror', name: 'Зеркала', description: 'Статусы и отображение', icon: 'Radio' },
  { id: 'utility', name: 'Утилиты', description: 'Модерация, варны и очистка', icon: 'Wrench' },
];

export interface UnifiedCommandDefinition {
  id: string;
  name: string;
  prefix: CommandPrefix;
  title: string;
  description: string;
  category: CommandCategory;
  usage: string;
  example: string;
  enabled: boolean;
  disabledReason?: string;
  requiresReply: boolean;
  requiresArguments: boolean;
  requiresConnection: boolean;
  requiresAI: boolean;
  requiresMedia: boolean;
  requiredPermissions: string[];
  responseMode: ResponseMode;
  uiRoute?: string;
  telegramMenu: boolean;
  handlerIdentifier: string;
}

export function isAiProviderConfigured(): boolean {
  return Boolean(process.env.OPENAI_API_KEY || process.env.GEMINI_API_KEY);
}

export const UNIFIED_COMMANDS: UnifiedCommandDefinition[] = [
  // ============================================================
  // ОСНОВНЫЕ
  // ============================================================
  {
    id: 'start',
    name: 'start',
    prefix: '/',
    title: 'Старт',
    description: 'Главное меню и запуск приложения SerkoGram',
    category: 'main',
    usage: '/start [payload]',
    example: '/start',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    uiRoute: '/',
    telegramMenu: true,
    handlerIdentifier: 'handleStart',
  },
  {
    id: 'help',
    name: 'help',
    prefix: '.|/',
    title: 'Помощь',
    description: 'Справочное руководство и список команд',
    category: 'main',
    usage: '.help или /help',
    example: '.help',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    uiRoute: '/instructions',
    telegramMenu: true,
    handlerIdentifier: 'handleHelp',
  },
  {
    id: 'commands',
    name: 'commands',
    prefix: '.|/',
    title: 'Каталог команд',
    description: 'Полный интерактивный каталог всех команд SerkoGram',
    category: 'main',
    usage: '.commands или /commands',
    example: '.commands',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    uiRoute: '/commands',
    telegramMenu: true,
    handlerIdentifier: 'handleCommands',
  },
  {
    id: 'settings',
    name: 'settings',
    prefix: '.|/',
    title: 'Настройки',
    description: 'Параметры архивации, автосохранение и приватность',
    category: 'main',
    usage: '.settings или /settings',
    example: '.settings',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    uiRoute: '/settings',
    telegramMenu: true,
    handlerIdentifier: 'handleSettings',
  },

  // ============================================================
  // ИНФОРМАЦИЯ
  // ============================================================
  {
    id: 'info',
    name: 'info',
    prefix: '.|/',
    title: 'Информация',
    description: 'Сведения об авторе сообщения (по ответу) или о сервисе SerkoGram',
    category: 'info',
    usage: '.info (в ответ на сообщение) или /info',
    example: '.info',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'REPLY',
    uiRoute: '/faq',
    telegramMenu: true,
    handlerIdentifier: 'handleInfo',
  },

  // ============================================================
  // АРХИВ
  // ============================================================
  {
    id: 'archive',
    name: 'archive',
    prefix: '.|/',
    title: 'Архив переписки',
    description: 'Просмотр сохранённых чатов и сообщений текущего диалога',
    category: 'archive',
    usage: '.archive или /archive',
    example: '.archive',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: ['read_messages'],
    responseMode: 'MINI_APP',
    uiRoute: '/archive',
    telegramMenu: true,
    handlerIdentifier: 'handleArchive',
  },
  {
    id: 'deleted',
    name: 'deleted',
    prefix: '.|/',
    title: 'Удалённые сообщения',
    description: 'Список удалённых сообщений в текущем чате или архиве',
    category: 'archive',
    usage: '.deleted или /deleted',
    example: '.deleted',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: ['receive_deletions'],
    responseMode: 'MINI_APP',
    uiRoute: '/archive?filter=deleted',
    telegramMenu: true,
    handlerIdentifier: 'handleDeleted',
  },
  {
    id: 'media',
    name: 'media',
    prefix: '.|/',
    title: 'Медиатека',
    description: 'Просмотр сохранённых фото, видео, голосовых и документов',
    category: 'archive',
    usage: '.media или /media',
    example: '.media',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: ['read_messages'],
    responseMode: 'MINI_APP',
    uiRoute: '/archive?filter=media',
    telegramMenu: true,
    handlerIdentifier: 'handleMedia',
  },
  {
    id: 'search',
    name: 'search',
    prefix: '.|/',
    title: 'Поиск по архиву',
    description: 'Полнотекстовый поиск по переписке текущего чата',
    category: 'archive',
    usage: '.search <запрос> или /search <запрос>',
    example: '.search договор',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: ['read_messages'],
    responseMode: 'MINI_APP',
    uiRoute: '/archive?search=true',
    telegramMenu: true,
    handlerIdentifier: 'handleSearch',
  },

  // ============================================================
  // ИГРЫ
  // ============================================================
  {
    id: 'coin',
    name: 'coin',
    prefix: '.|/',
    title: 'Монетка',
    description: 'Бросок монетки: Орёл или Решка в текущий чат',
    category: 'games',
    usage: '.coin или /coin',
    example: '.coin',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleCoin',
  },
  {
    id: 'dice',
    name: 'dice',
    prefix: '.|/',
    title: 'Игральный кубик',
    description: 'Бросок анимированного игрального кубика Telegram (sendDice)',
    category: 'games',
    usage: '.dice или .дайс',
    example: '.dice',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleDice',
  },
  {
    id: 'dice_ru',
    name: 'дайс',
    prefix: '.',
    title: 'Игральный кубик (алиас)',
    description: 'Бросок анимированного игрального кубика Telegram',
    category: 'games',
    usage: '.дайс',
    example: '.дайс',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleDice',
  },
  {
    id: 'ttt',
    name: 'ttt',
    prefix: '.|/',
    title: 'Крестики-нолики',
    description: 'Интерактивная игра в крестики-нолики',
    category: 'games',
    usage: '.ttt или /ttt',
    example: '.ttt',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTicTacToe',
  },
  {
    id: 'rps',
    name: 'rps',
    prefix: '.|/',
    title: 'Камень-Ножницы-Бумага',
    description: 'Классическая игра против бота или собеседника',
    category: 'games',
    usage: '.rps [камень|ножницы|бумага]',
    example: '.rps камень',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleRps',
  },

  // ============================================================
  // НЕЙРОСЕТЬ (AI)
  // ============================================================
  {
    id: 'gpt',
    name: 'gpt',
    prefix: '.|/',
    title: 'Запрос к AI',
    description: 'Задать вопрос нейросети прямо в чате',
    category: 'ai',
    usage: '.gpt <вопрос>',
    example: '.gpt Напиши короткий план встречи',
    enabled: false,
    disabledReason: 'Требуется подключение AI-провайдера (OPENAI_API_KEY)',
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: false,
    requiresAI: true,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleGpt',
  },
  {
    id: 'a_gpt',
    name: 'a_gpt',
    prefix: '.|/',
    title: 'Авто-AI ответчик',
    description: 'Включить автоматические AI-ответы в выбранном чате',
    category: 'ai',
    usage: '.a_gpt',
    example: '.a_gpt',
    enabled: false,
    disabledReason: 'Требуется подключение AI-провайдера (OPENAI_API_KEY)',
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: true,
    requiresMedia: false,
    requiredPermissions: ['can_reply'],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleAutoGpt',
  },
  {
    id: 'a_gpt_off',
    name: 'a_gpt_off',
    prefix: '.|/',
    title: 'Отключить Авто-AI',
    description: 'Отключить автоматические AI-ответы в чате',
    category: 'ai',
    usage: '.a_gpt_off',
    example: '.a_gpt_off',
    enabled: false,
    disabledReason: 'Требуется подключение AI-провайдера (OPENAI_API_KEY)',
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: true,
    requiresMedia: false,
    requiredPermissions: ['can_reply'],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleAutoGptOff',
  },
  {
    id: 'image',
    name: 'image',
    prefix: '.|/',
    title: 'Генерация картинок',
    description: 'Создание изображения по текстовому описанию',
    category: 'ai',
    usage: '.image <описание>',
    example: '.image Неоновый город под дождём',
    enabled: false,
    disabledReason: 'Требуется подключение AI-провайдера (OPENAI_API_KEY)',
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: false,
    requiresAI: true,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleImage',
  },

  // ============================================================
  // ПЕРЕВОД (TRANSLATION)
  // ============================================================
  {
    id: 'translate',
    name: 'перевод',
    prefix: '.',
    title: 'Перевод сообщений',
    description: 'Включить автоматический перевод сообщений в текущем чате (en, ru, de, etc.) или отключить (off)',
    category: 'translation',
    usage: '.перевод [код_языка|off]',
    example: '.перевод en',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: ['can_reply'],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTranslation',
  },

  // ============================================================
  // АНИМАЦИИ
  // ============================================================
  {
    id: 'fco',
    name: 'fco',
    prefix: '.|/',
    title: 'Анимация текста',
    description: 'Генерация анимированной цитаты и текстового оформления',
    category: 'animations',
    usage: '.fco или /fco',
    example: '.fco',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleFco',
  },
  {
    id: 'anim_p',
    name: 'p',
    prefix: '.|/',
    title: 'Пиксельный баннер',
    description: 'Отрисовка стилизованного пиксельного баннера SerkoGram',
    category: 'animations',
    usage: '.p или /p',
    example: '.p',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleP',
  },
  {
    id: 'anim_love',
    name: 'love',
    prefix: '.',
    title: 'Анимация любви',
    description: 'Отправка сердечного признания с оформлением',
    category: 'animations',
    usage: '.love',
    example: '.love',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleLove',
  },
  {
    id: 'anim_love2',
    name: 'love2',
    prefix: '.',
    title: 'Радужные сердца',
    description: 'Каскадная радужная анимация сердец',
    category: 'animations',
    usage: '.love2',
    example: '.love2',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleLove2',
  },
  {
    id: 'anim_minus7',
    name: '-7',
    prefix: '.',
    title: 'Канеки 1000-7',
    description: 'Легендарный обратный отсчёт Tokyo Ghoul (1000 - 7)',
    category: 'animations',
    usage: '.-7',
    example: '.-7',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleMinus7',
  },

  // ============================================================
  // МЕДИА & EPHEMERAL MEDIA
  // ============================================================
  {
    id: 'save',
    name: 'save',
    prefix: '.|/',
    title: 'Сохранить в архив',
    description: 'Принудительно сохранить ответное медиа (включая одноразовое / исчезающее фото или видео) в защищённый архив',
    category: 'media',
    usage: '.save (в ответ на медиа/сообщение) или .save <URL>',
    example: '.save',
    enabled: true,
    requiresReply: true,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: true,
    requiredPermissions: ['read_messages'],
    responseMode: 'OWNER_PRIVATE',
    uiRoute: '/archive',
    telegramMenu: false,
    handlerIdentifier: 'handleSave',
  },
  {
    id: 'voice',
    name: 'гс',
    prefix: '.|/',
    title: 'Голосовые заметки',
    description: 'Расшифровка или фиксация голосового сообщения (в ответ на аудио/voice)',
    category: 'media',
    usage: '.гс (в ответ на аудио)',
    example: '.гс',
    enabled: false,
    disabledReason: 'Требуется подключение провайдера обработки аудио',
    requiresReply: true,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: true,
    requiredPermissions: ['read_messages'],
    responseMode: 'REPLY',
    uiRoute: '/archive?filter=voice',
    telegramMenu: false,
    handlerIdentifier: 'handleVoice',
  },

  // ============================================================
  // ПРИКОЛЫ & РАЗВЛЕЧЕНИЯ (С ОГРАНИЧЕНИЯМИ)
  // ============================================================
  {
    id: 'spam',
    name: 'spam',
    prefix: '.|/',
    title: 'Защита от спама',
    description: 'Тест системы защиты от флуда и ограничений Telegram',
    category: 'fun',
    usage: '.spam [кол-во до 3]',
    example: '.spam 3',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleSpam',
  },
  {
    id: 'troll',
    name: 'troll',
    prefix: '.|/',
    title: 'Шуточный ответ',
    description: 'Безобидный шуточный ответ с системным кулдауном',
    category: 'fun',
    usage: '.troll',
    example: '.troll',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTroll',
  },
  {
    id: 'a_troll',
    name: 'a_troll',
    prefix: '.|/',
    title: 'Шуточный автоответчик',
    description: 'Статус шуточного автоответчика с лимитом срабатываний',
    category: 'fun',
    usage: '.a_troll',
    example: '.a_troll',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleAutoTroll',
  },
  {
    id: 'trol_alias',
    name: 'trol',
    prefix: '.',
    title: 'Шуточный ответ (алиас)',
    description: 'Алиас команды .troll',
    category: 'fun',
    usage: '.trol',
    example: '.trol',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTroll',
  },
  {
    id: 'tyuring',
    name: 'tyuring',
    prefix: '.',
    title: 'Тест Тьюринга',
    description: 'Интеллектуальный шуточный диалог на проверку искусственного интеллекта',
    category: 'fun',
    usage: '.tyuring',
    example: '.tyuring',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: false,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTyuring',
  },

  // ============================================================
  // ЗЕРКАЛА / АВТОМАТИЗАЦИЯ
  // ============================================================
  {
    id: 'online',
    name: 'online',
    prefix: '.',
    title: 'Вечный онлайн',
    description: 'Статус режима удержания онлайн (доступность зависит от прав клиента)',
    category: 'mirror',
    usage: '.online',
    example: '.online',
    enabled: false,
    disabledReason: 'Функция требует прямого MTProto-подключения клиента',
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleOnline',
  },
  {
    id: 'autotyping',
    name: 'autotyping',
    prefix: '.',
    title: 'Авто-печатание',
    description: 'Индикация статуса набора текста в активном диалоге',
    category: 'mirror',
    usage: '.autotyping [on|off]',
    example: '.autotyping on',
    enabled: false,
    disabledReason: 'Функция требует прямого MTProto-подключения клиента',
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleAutoTyping',
  },
  {
    id: 'autovoice',
    name: 'autovoice',
    prefix: '.',
    title: 'Авто-запись голоса',
    description: 'Индикация статуса записи аудио в диалоге',
    category: 'mirror',
    usage: '.autovoice [on|off]',
    example: '.autovoice on',
    enabled: false,
    disabledReason: 'Функция требует прямого MTProto-подключения клиента',
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleAutoVoice',
  },
  {
    id: 'warn',
    name: 'warn',
    prefix: '.',
    title: 'Предупреждение (Варн)',
    description: 'Выдать предупреждение участнику чата в ответ на его сообщение',
    category: 'utility',
    usage: '.warn [причина]',
    example: '.warn спам',
    enabled: true,
    requiresReply: true,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleWarn',
  },
  {
    id: 'mute',
    name: 'mute',
    prefix: '.',
    title: 'Мут участника',
    description: 'Ограничение отправки сообщений для участника в группе или управляемом чате',
    category: 'utility',
    usage: '.mute [время]',
    example: '.mute 10',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleMute',
  },
  {
    id: 'unmute',
    name: 'unmute',
    prefix: '.',
    title: 'Снятие ограничений (Размут)',
    description: 'Снятие ограничений и возобновление нормального приёма сообщений',
    category: 'utility',
    usage: '.unmute',
    example: '.unmute',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleMute',
  },
  {
    id: 'panic',
    name: 'panic',
    prefix: '.',
    title: 'Режим паники',
    description: 'Экстренный режим защиты текущего чата в SerkoGram',
    category: 'utility',
    usage: '.panic',
    example: '.panic',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handlePanic',
  },
  {
    id: 'unpanic',
    name: 'unpanic',
    prefix: '.',
    title: 'Отключение режима паники',
    description: 'Возврат диалога в нормальный режим работы',
    category: 'utility',
    usage: '.unpanic',
    example: '.unpanic',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handlePanic',
  },
  {
    id: 'snos',
    name: 'snos',
    prefix: '.',
    title: 'Очистить архив SerkoGram',
    description: 'Безопасное удаление сохранённого архива SerkoGram с обязательным подтверждением',
    category: 'utility',
    usage: '.snos',
    example: '.snos',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleSnos',
  },
  {
    id: 'clone',
    name: 'clone',
    prefix: '.',
    title: 'Клонировать сообщение',
    description: 'Дублирование ответного сообщения в текущем чате',
    category: 'utility',
    usage: '.clone',
    example: '.clone',
    enabled: false,
    disabledReason: 'Не поддерживается Telegram Bot API',
    requiresReply: true,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleClone',
  },
  {
    id: 'timer',
    name: 'timer',
    prefix: '.',
    title: 'Таймер в чате',
    description: 'Установить таймер-напоминание в секундах',
    category: 'automation',
    usage: '.timer <секунды> [заметка]',
    example: '.timer 60 перезвонить',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTimer',
  },
  {
    id: 'typing',
    name: 'typing',
    prefix: '.',
    title: 'Статус набора текста',
    description: 'Отправка индикатора набора текста в текущий чат',
    category: 'automation',
    usage: '.typing [on|off]',
    example: '.typing on',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTyping',
  },
  {
    id: 'profile',
    name: 'profile',
    prefix: '.',
    title: 'Профиль SerkoGram',
    description: 'Информация о вашей учётной записи и текущих параметрах архива',
    category: 'info',
    usage: '.profile',
    example: '.profile',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleProfile',
  },
  {
    id: 'fix',
    name: 'fix',
    prefix: '.',
    title: 'AI Корректор',
    description: 'Исправление грамматики, пунктуации и стиля текста',
    category: 'ai',
    usage: '.fix <текст> или в ответ на сообщение',
    example: '.fix превет как дила',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: true,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleFix',
  },
  {
    id: 'stt',
    name: 'stt',
    prefix: '.',
    title: 'Speech to Text',
    description: 'Расшифровка голосового сообщения или видеозаметки в текст',
    category: 'ai',
    usage: '.stt (в ответ на аудио/гс)',
    example: '.stt',
    enabled: false,
    disabledReason: 'Требуется подключение Whisper / Google STT API',
    requiresReply: true,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: true,
    requiresMedia: true,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleStt',
  },
  {
    id: 'tr',
    name: 'tr',
    prefix: '.',
    title: 'Быстрый перевод',
    description: 'Перевод текста на указанный язык',
    category: 'translation',
    usage: '.tr <код_языка> <текст>',
    example: '.tr en привет мир',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleTr',
  },
  {
    id: 'vnote',
    name: 'vnote',
    prefix: '.',
    title: 'Видео в кружок',
    description: 'Конвертация квадратного видеосообщения в видеозаметку (кружок)',
    category: 'media',
    usage: '.vnote (в ответ на видео)',
    example: '.vnote',
    enabled: false,
    disabledReason: 'Требуется серверная обработка FFmpeg',
    requiresReply: true,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: true,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleVnote',
  },
  {
    id: 'vreverse',
    name: 'vreverse',
    prefix: '.',
    title: 'Реверс видео',
    description: 'Воспроизведение видео в обратном порядке',
    category: 'media',
    usage: '.vreverse (в ответ на видео)',
    example: '.vreverse',
    enabled: false,
    disabledReason: 'Требуется серверная обработка FFmpeg',
    requiresReply: true,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: true,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleVreverse',
  },
  {
    id: 'dem',
    name: 'dem',
    prefix: '.',
    title: 'Демотиватор',
    description: 'Генерация демотиватора из текста или изображения',
    category: 'media',
    usage: '.dem <заголовок> | <подпись>',
    example: '.dem УСПЕХ | Это просто случайность',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleDem',
  },
  {
    id: 'art',
    name: 'art',
    prefix: '.',
    title: 'ASCII Арт',
    description: 'Преобразование текста в красивый ASCII/Braille баннер',
    category: 'media',
    usage: '.art <текст>',
    example: '.art SerkoGram',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleArt',
  },
  {
    id: 'fake',
    name: 'fake',
    prefix: '.',
    title: 'Шаблон цитаты',
    description: 'Создание стилизованной цитаты/шаблона для развлекательных целей',
    category: 'fun',
    usage: '.fake <текст>',
    example: '.fake Сегодня выходной!',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleFake',
  },
  {
    id: 'pet',
    name: 'pet',
    prefix: '.',
    title: 'Погладить',
    description: 'Отправить тёплую реакцию или погладить собеседника',
    category: 'fun',
    usage: '.pet [имя]',
    example: '.pet',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handlePet',
  },
  {
    id: 'wanted',
    name: 'wanted',
    prefix: '.',
    title: 'Разыскивается (Wanted)',
    description: 'Шуточный постер "Разыскивается" с наградой',
    category: 'fun',
    usage: '.wanted <имя или в ответ>',
    example: '.wanted Иван',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleWanted',
  },
  {
    id: 'agro',
    name: 'agro',
    prefix: '.',
    title: 'Агро-режим',
    description: 'Шуточный дерзкий ответ (с ограничением по тайм-ауту)',
    category: 'fun',
    usage: '.agro',
    example: '.agro',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleAgro',
  },
  {
    id: 'spoiler',
    name: 'spoiler',
    prefix: '.',
    title: 'Текст под спойлер',
    description: 'Обернуть текст в скрытый спойлер Telegram',
    category: 'animations',
    usage: '.spoiler <текст>',
    example: '.spoiler Секретное сообщение',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleSpoiler',
  },
  {
    id: 'flip',
    name: 'flip',
    prefix: '.',
    title: 'Перевёрнутый текст',
    description: 'Перевернуть текст вверх ногами (uʍop ǝpısdn)',
    category: 'animations',
    usage: '.flip <текст>',
    example: '.flip Привет мир',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleFlip',
  },
  {
    id: 'bubble',
    name: 'bubble',
    prefix: '.',
    title: 'Текст в кружочках',
    description: 'Трансформация букв в кружочки (ⓑⓤⓑⓑⓛⓔ)',
    category: 'animations',
    usage: '.bubble <текст>',
    example: '.bubble SerkoGram',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleBubble',
  },
  {
    id: 'nospace',
    name: 'nospace',
    prefix: '.',
    title: 'Текст без пробелов',
    description: 'Удаление всех пробелов из текста',
    category: 'animations',
    usage: '.nospace <текст>',
    example: '.nospace Пишем слитно всё',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleNoSpace',
  },
  {
    id: 'dumb',
    name: 'dumb',
    prefix: '.',
    title: 'ЗаБоРчИк',
    description: 'Чередование заглавных и строчных букв',
    category: 'animations',
    usage: '.dumb <текст>',
    example: '.dumb Очень умный текст',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleDumb',
  },
  {
    id: 'leet',
    name: 'leet',
    prefix: '.',
    title: '1337 H4x0r',
    description: 'Трансформация текста в хакерский стиль 1337',
    category: 'animations',
    usage: '.leet <текст>',
    example: '.leet elite hacker',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleLeet',
  },
  {
    id: 'zalgo',
    name: 'zalgo',
    prefix: '.',
    title: 'Zalgo глитч',
    description: 'Наложение хаотичных глитч-символов Zalgo',
    category: 'animations',
    usage: '.zalgo <текст>',
    example: '.zalgo Хаос наступает',
    enabled: true,
    requiresReply: false,
    requiresArguments: true,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleZalgo',
  },
  {
    id: 'heart',
    name: 'heart',
    prefix: '.',
    title: 'Сердечки',
    description: 'Красивый узор из сердечек',
    category: 'animations',
    usage: '.heart',
    example: '.heart',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handleHeart',
  },
  {
    id: 'plove',
    name: 'plove',
    prefix: '.',
    title: 'Признание в любви',
    description: 'Тёплое признание с анимацией сердец',
    category: 'animations',
    usage: '.plove [имя]',
    example: '.plove Аня',
    enabled: true,
    requiresReply: false,
    requiresArguments: false,
    requiresConnection: true,
    requiresAI: false,
    requiresMedia: false,
    requiredPermissions: [],
    responseMode: 'SAME_CHAT',
    telegramMenu: false,
    handlerIdentifier: 'handlePlove',
  },
];

export function getAllCommands(): UnifiedCommandDefinition[] {
  return UNIFIED_COMMANDS;
}

export function getDotCommands(): UnifiedCommandDefinition[] {
  return UNIFIED_COMMANDS.filter((c) => c.prefix.includes('.'));
}

export function getSlashCommands(): UnifiedCommandDefinition[] {
  return UNIFIED_COMMANDS.filter((c) => c.prefix.includes('/'));
}

export function getTelegramMenuCommands(): { command: string; description: string }[] {
  return UNIFIED_COMMANDS.filter((c) => c.telegramMenu && c.enabled).map((c) => ({
    command: c.name,
    description: c.description,
  }));
}

export function getCommandByName(name: string, prefix?: '.' | '/'): UnifiedCommandDefinition | undefined {
  const normalized = name.trim().toLowerCase().replace(/^[./]/, '');
  return UNIFIED_COMMANDS.find((c) => {
    const nameMatches = c.name.toLowerCase() === normalized;
    if (!nameMatches) return false;
    if (prefix && !c.prefix.includes(prefix)) return false;
    return true;
  });
}

export function getCommandsByCategory(category: CommandCategory): UnifiedCommandDefinition[] {
  return UNIFIED_COMMANDS.filter((c) => c.category === category);
}